services:
  postgres:
    image: "postgres:latest"
    container_name: jeftavares-postgres
    environment:
      - POSTGRES_USER=jeftavares
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./PGData:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jef-brewmaster-net

networks:
  jef-brewmaster-net:
    driver: bridge
