CREATE TABLE categoria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_categoria varchar(50) UNIQUE NOT NULL
);

CREATE TABLE genero (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_genero varchar(50) UNIQUE NOT NULL
);

CREATE TABLE status (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_nome varchar(50) UNIQUE NOT NULL
);

CREATE TABLE editora (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) UNIQUE NOT NULL,
  biografia text,
  url_logo varchar(3000),
  site_oficial varchar(200)
);

CREATE TABLE pais (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) UNIQUE NOT NULL,
  codigo_iso char(3) UNIQUE NOT NULL,
  regiao VARCHAR(100),
  populacao integer,
  area_km2 decimal
);

CREATE TABLE revista (
  id BIGSERIAL PRIMARY KEY,
  nome varchar(150),
  categoria_id integer,
  genero_id integer,
  status_id integer,
  editora_id bigserial NOT NULL,
  pais_id integer
);

CREATE TABLE revista_edicoes (
  id BIGSERIAL PRIMARY KEY,
  revista_id bigserial,
  numero int,
  num_paginas int,
  data_publicacao date,
  url_cap varchar(3000)
);

CREATE TABLE autor (
  id BIGSERIAL PRIMARY KEY,
  nome varchar(150) NOT NULL,
  biografia text,
  pais_nascimento integer,
  data_nascimento date,
  data_falecimento date
);

CREATE TABLE quadrinho_autores (
  id_autor bigserial,
  id_quadrinho bigserial,
  trabalho varchar NOT NULL,
  PRIMARY KEY (id_autor, id_quadrinho)
);

CREATE TABLE quadrinho (
  id BIGSERIAL PRIMARY KEY,
  titulo varchar(250) NOT NULL,
  numero int,
  num_paginas int,
  data_publicacao date,
  editora_id bigserial,
  licenciado_por bigserial,
  categoria integer,
  genero integer,
  status_id integer
);

CREATE TABLE quadrinho_revistas (
  id_quadrinho bigserial,
  id_revista bigserial,
  PRIMARY KEY (id_quadrinho, id_revista)
);

CREATE TABLE colecao (
  id BIGSERIAL,
  quadrinho_id integer UNIQUE,
  name varchar(250) UNIQUE NOT NULL,
  status integer,
  PRIMARY KEY (id, quadrinho_id)
);

ALTER TABLE revista ADD FOREIGN KEY (categoria_id) REFERENCES categoria (id);

ALTER TABLE revista ADD FOREIGN KEY (genero_id) REFERENCES genero (id);

ALTER TABLE revista ADD FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE revista ADD FOREIGN KEY (editora_id) REFERENCES editora (id);

ALTER TABLE revista ADD FOREIGN KEY (pais_id) REFERENCES pais (id);

ALTER TABLE revista_edicoes ADD FOREIGN KEY (revista_id) REFERENCES revista (id);

ALTER TABLE autor ADD FOREIGN KEY (pais_nascimento) REFERENCES pais (id);

ALTER TABLE quadrinho_autores ADD FOREIGN KEY (id_autor) REFERENCES autor (id);

ALTER TABLE quadrinho_autores ADD FOREIGN KEY (id_quadrinho) REFERENCES quadrinho (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (editora_id) REFERENCES editora (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (licenciado_por) REFERENCES editora (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (categoria) REFERENCES categoria (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (genero) REFERENCES genero (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE quadrinho_revistas ADD FOREIGN KEY (id_quadrinho) REFERENCES quadrinho (id);

ALTER TABLE quadrinho_revistas ADD FOREIGN KEY (id_revista) REFERENCES revista (id);

ALTER TABLE colecao ADD FOREIGN KEY (quadrinho_id) REFERENCES quadrinho (id);

ALTER TABLE colecao ADD FOREIGN KEY (status) REFERENCES status (id);
