CREATE TABLE categoria (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(50) UNIQUE NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genero (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_genero varchar(50) UNIQUE NOT NULL
);

CREATE TABLE status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_status varchar(50) UNIQUE NOT NULL
);

CREATE TABLE editora (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) UNIQUE NOT NULL,
  biografia text,
  url_logo varchar(3000),
  site_oficial varchar(200)
);

CREATE TABLE pais (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(100) UNIQUE NOT NULL,
  codigo_iso char(3) UNIQUE NOT NULL,
  regiao VARCHAR(100),
  populacao integer,
  area_km2 decimal
);

CREATE TABLE revista (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150),
  categoria_id bigint,
  genero_id bigint,
  status_id bigint,
  editora_id bigint NOT NULL,
  pais_id bigint
);

CREATE TABLE revista_edicoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  revista_id bigint,
  numero int,
  num_paginas int,
  data_publicacao date,
  url_cap varchar(3000)
);

CREATE TABLE autor (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  biografia text,
  pais_nascimento_id bigint,
  data_nascimento date,
  data_falecimento date
);

CREATE TABLE quadrinho_autores (
  autor_id bigint,
  quadrinho_id bigint,
  trabalho tipo_trabalho NOT NULL 
  PRIMARY KEY (autor_id, quadrinho_id)
);

CREATE TABLE quadrinho (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo varchar(250) NOT NULL,
  numero int,
  num_paginas int,
  data_publicacao date,
  editora_id bigint,
  licenciado_por bigint,
  categoria_id integer,
  genero_id integer,
  status_id integer
);

CREATE TABLE quadrinho_revistas (
  quadrinho_id bigint,
  revista_id bigint,
  PRIMARY KEY (quadrinho_id, revista_id)
);

CREATE TABLE colecao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quadrinho_id bigint UNIQUE,
  name varchar(250) UNIQUE NOT NULL,
  status_id bigint
);

CREATE TABLE lista_desejo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quadrinho_id bigint UNIQUE,
  nome varchar(250) UNIQUE NOT NULL,
);

CREATE TABLE lista_desejo_lojas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lista_desejo_id bigint
  url varchar(3000),
  preco decimal
)

-- Adicionar índices
CREATE INDEX idx_quadrinho_titulo ON quadrinho(titulo);
CREATE INDEX idx_quadrinho_data_publicacao ON quadrinho(data_publicacao);

-- Adicionar constraints
ALTER TABLE autor ADD CONSTRAINT check_datas_validas 
  CHECK (data_falecimento IS NULL OR data_falecimento > data_nascimento);

-- Adicionar comentários
COMMENT ON TABLE quadrinho IS 'Armazena informações sobre quadrinhos individuais';
COMMENT ON COLUMN quadrinho.titulo IS 'Título principal do quadrinho';

ALTER TABLE revista ADD FOREIGN KEY (categoria_id) REFERENCES categoria (id);

ALTER TABLE revista ADD FOREIGN KEY (genero_id) REFERENCES genero (id);

ALTER TABLE revista ADD FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE revista ADD FOREIGN KEY (editora_id) REFERENCES editora (id);

ALTER TABLE revista ADD FOREIGN KEY (pais_id) REFERENCES pais (id);

ALTER TABLE revista_edicoes ADD FOREIGN KEY (revista_id) REFERENCES revista (id);

ALTER TABLE autor ADD FOREIGN KEY (pais_nascimento_id) REFERENCES pais (id);

ALTER TABLE quadrinho_autores ADD FOREIGN KEY (autor_id) REFERENCES autor (id);

ALTER TABLE quadrinho_autores ADD FOREIGN KEY (quadrinho_id) REFERENCES quadrinho (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (editora_id) REFERENCES editora (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (licenciado_por) REFERENCES editora (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (categoria_id) REFERENCES categoria (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (genero_id) REFERENCES genero (id);

ALTER TABLE quadrinho ADD FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE quadrinho_revistas ADD FOREIGN KEY (quadrinho_id) REFERENCES quadrinho (id);

ALTER TABLE quadrinho_revistas ADD FOREIGN KEY (revista_id) REFERENCES revista (id);

ALTER TABLE colecao ADD FOREIGN KEY (quadrinho_id) REFERENCES quadrinho (id);

ALTER TABLE colecao ADD FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE lista_desejo ADD FOREIGN KEY (quadrinho_id) REFERENCES quadrinho (id);

ALTER TABLE lista_desejo_lojas ADD FOREIGN KEY (lista_desejo_id) REFERENCES lista_desejo (id);

CREATE TYPE tipo_trabalho AS ENUM ('roteirista', 'desenhista', 'colorista');

